@startuml

title Solution TrainingLog

node Nuget.org{
    [TrainingLog.Contract]
    [SportsTracker.SDK]
}

node PowershellGallery{
    [TrainingLog.Endomondo]
    [TrainingLog.SportsTracker]
    [SportTrackerCmdlet]
}

node Sports-Tracker{
    [Sports-Tracker.Api]
}


node ProductivityTools.Server{
    [TrainingLog.Api]
}

node Server{
    database "SQL\n" {
    [Data]

}

 [TrainingLog.SportsTracker] -down->[SportsTracker.SDK]
 [SportsTracker.SDK] -down->[Sports-Tracker.Api]
 [TrainingLog.Endomondo] -down->[TrainingLog.Contract]
 [TrainingLog.Contract] -down->  [TrainingLog.Api]
 [TrainingLog.SportsTracker] -down-> [TrainingLog.Contract]
 [TrainingLog.Api] -down->Data
 [SportTrackerCmdlet] -down->[SportsTracker.SDK]
 
 



@enduml