CREATE TABLE Training
(
	TrainingId INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(200) NULL,
	Comments VARCHAR(1000) NULL,
	Sport VARCHAR(100) NOT NULL,
	Source VARCHAR(20) NOT NULL,
	[Start] DATETIME NOT NULL,
	[End] DATETIME NOT NULL,
	Duration INT NOT NULL,
	Distance FLOAT NULL,
	Calories FLOAT NULL,
	AverageSpeed FLOAT NULL,
)