CREATE TABLE Gpx
(
	GpxId INT IDENTITY(1,1) PRIMARY KEY,
	TrainingId INT,
	GpxFileHash VARBINARY (MAX) NULL,
	GpxFile VARBINARY (MAX) NULL,

	CONSTRAINT FK_Gpx_Training FOREIGN KEY (TrainingId) REFERENCES Training(TrainingId)
)